Add automatic function discovery
haroldadmin/functions-differ pull request #11
Opened 2022-04-11 10:55 UTC by hiiambhanu

1. Added a `--discover` flag which is a `Boolean`, indicating whether or not we want to use automatic functions and path discovery.
2. Added another argument called `indexFilePath` which points to the location of the `index.ts file` which exports all the functions (ususally the `src/index.ts` file). This arg is optional and is only used when used with `--discover` flag.
3. If the discover flag is used, it uses the `ts-morph` script to get function paths and rewrites the "functions section" of `.differspec.json` file.

2022-04-21 05:10 UTC, haroldadmin requested changes
There's a few nitpicks I pointed out in the review, but it looks great overall. Thanks for contributing this feature!

2022-04-21 05:10 UTC, haroldadmin commented on src/discoverer/discoverer.spec.ts
> +    this.timeout(0);
Why is this needed?

2022-04-21 05:10 UTC, haroldadmin commented on src/discoverer/discoverer.ts
> +    return undefined;
This is the same as `return sourceFile`?

2022-04-21 05:10 UTC, haroldadmin commented on src/discoverer/discoverer.ts
> +export { getExports as getFirebaseFunctionsAndPaths };
Prefer adding whitespace before exports

2022-04-21 06:29 UTC, hiiambhanu commented on src/discoverer/discoverer.spec.ts
> +    this.timeout(0);
The test was timing out on my machine (which was kinda low on resources when I was running it) so had to increase the timeout. Moreover, depending on the complexity of the project, function discovery may take time longer than 3000ms which, I think was the default timeout for this test.

2022-04-25 02:53 UTC, haroldadmin approved these changes
LGTM! Really appreciate that you updated the docs too.

2022-04-25 02:53 UTC, merged